### PR TITLE
Removed "user-scalable=no"

### PR DESCRIPTION
**Pull request by LukyVj**
The user should always have the choice to zoom.
I think it'd be better to remove it 😊

### CODE REVIEW

**Comment by Haroenv** [comment]
remove `maximum-scale` too then, right?

**Comment by LukyVj** [comment]
Not sure 🤔

**Comment by JohJakob** [comment]
@LukyVj It's only for mobile devices. In my opinion you shouldn't zoom on responsive websites because you can't zoom apps too. It probably makes sense for some websites, but not for this one. But that's just my opinion. Feel free to change it.

**Comment by mischah** [comment]
Same thing like `target="_blank".
Please, let the user decide :smirk:

**Comment by mischah** [comment]
Almost forgot: super awesome loader :ok_hand:

**Comment by JohJakob** [comment]
@mischah Thanks!

**Pull request merged**
